"""empty message

Revision ID: 2eaac481017f
Revises: 543f3a576dd4
Create Date: 2019-10-11 18:46:43.055277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaac481017f'
down_revision = '543f3a576dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expected', sa.Column('nickname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expected', 'nickname')
    # ### end Alembic commands ###
