"""empty message

Revision ID: 4301a102b264
Revises: d707ef1688fe
Create Date: 2019-09-26 14:43:01.282858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4301a102b264'
down_revision = 'd707ef1688fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expected', sa.Column('operatingDistribution', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expected', 'operatingDistribution')
    # ### end Alembic commands ###
