"""empty message

Revision ID: 543f3a576dd4
Revises: 4301a102b264
Create Date: 2019-09-26 17:21:51.754366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543f3a576dd4'
down_revision = '4301a102b264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expected', sa.Column('interest', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expected', 'interest')
    # ### end Alembic commands ###
