"""empty message

Revision ID: 90f576abaaf4
Revises: 
Create Date: 2019-10-20 21:54:46.606932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f576abaaf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ClassE', sa.Float(), nullable=True),
    sa.Column('ClassF', sa.Float(), nullable=True),
    sa.Column('ClassG', sa.Float(), nullable=True),
    sa.Column('ClassH', sa.Float(), nullable=True),
    sa.Column('ClassA', sa.Float(), nullable=True),
    sa.Column('ClassN', sa.Float(), nullable=True),
    sa.Column('ClassQ', sa.Float(), nullable=True),
    sa.Column('ClassS', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('expected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=1024), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('intclass', sa.String(length=1024), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('donation', sa.String(length=1024), nullable=True),
    sa.Column('spending', sa.String(length=1024), nullable=True),
    sa.Column('recap', sa.String(length=1024), nullable=True),
    sa.Column('distribution', sa.String(length=1024), nullable=True),
    sa.Column('operatingDistribution', sa.String(length=1024), nullable=True),
    sa.Column('timeframe', sa.Integer(), nullable=True),
    sa.Column('addContribution', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expected')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('interest_rates')
    # ### end Alembic commands ###
