"""Expected returns

Revision ID: c98509f1544e
Revises: 4635bf8f2e08
Create Date: 2019-09-19 18:36:25.343695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98509f1544e'
down_revision = '4635bf8f2e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=1024), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('intclass', sa.String(length=1024), nullable=True),
    sa.Column('donation', sa.String(length=1024), nullable=True),
    sa.Column('spending', sa.String(length=1024), nullable=True),
    sa.Column('recap', sa.String(length=1024), nullable=True),
    sa.Column('distribution', sa.String(length=1024), nullable=True),
    sa.Column('timeframe', sa.Integer(), nullable=True),
    sa.Column('addContribution', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expected')
    # ### end Alembic commands ###
