"""empty message

Revision ID: d488d7793916
Revises: 9157cb938176
Create Date: 2019-09-25 17:10:56.435876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd488d7793916'
down_revision = '9157cb938176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expected_id'), 'expected', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expected_id'), table_name='expected')
    # ### end Alembic commands ###
