"""empty message

Revision ID: d707ef1688fe
Revises: d488d7793916
Create Date: 2019-09-26 14:21:29.110395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd707ef1688fe'
down_revision = 'd488d7793916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expected_id', table_name='expected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_expected_id', 'expected', ['id'], unique=False)
    # ### end Alembic commands ###
