"""empty message

Revision ID: f21babcd3958
Revises: 
Create Date: 2019-09-14 13:34:33.567610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21babcd3958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ClassE', sa.Float(), nullable=True),
    sa.Column('ClassF', sa.Float(), nullable=True),
    sa.Column('ClassG', sa.Float(), nullable=True),
    sa.Column('ClassH', sa.Float(), nullable=True),
    sa.Column('ClassA', sa.Float(), nullable=True),
    sa.Column('ClassN', sa.Float(), nullable=True),
    sa.Column('ClassQ', sa.Float(), nullable=True),
    sa.Column('ClassS', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('interest_rates')
    # ### end Alembic commands ###
